application/application/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user_payment.views import stripe_webhook

urlpatterns = [
    path("", include('core.urls')),
    path("oferty/", include('item.urls')),
    path("dashboard/", include('dashboard.urls')),
    path("payment/", include('user_payment.urls')),
    path("chat/", include('chat.urls')),
	path('stripe_webhook', stripe_webhook, name='stripe_webhook'),
    path("dostawa/", include('delivery.urls')),
    path("admin/", admin.site.urls),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

application/chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path("", views.index, name='chat'),
    path("create-room/<str:uuid>", views.create_room, name='create-room'),
    path("chat-admin/", views.chat_admin, name="chat-admin")
]

application/dashboard/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views
from item import views as item_views

app_name = 'dashboard'

urlpatterns = [
    path("", views.user_items, name='user-items'),
    path("<int:pk>/delete/", item_views.delete, name="delete"),
    path("<int:pk>/edit/", item_views.edit_item, name="edit"),
]

application/item/urls.py
from django.urls import path
from . import views

app_name = "item"

urlpatterns = [
    path("", views.items, name="items"),
    path("nowa-oferta/", views.new_item, name="new-item"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/edit/", views.edit_item, name="edit"),
    path("edit-offers/", views.edit_items, name="edit-offers"),
    path('favorite/<int:pk>/', views.toggle_favorite, name='favorite'),
]

application/dashboard/views.py
from django.shortcuts import render
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from item.models import Item, Image, GENRES


@login_required
def user_items(request):
    filter_items = Item.objects.filter(created_by=request.user)

    # Name filter
    if name := request.GET.get('offername', ''):
        filter_items = filter_items.filter(Q(name__icontains=name))

    # Format filter
    if format_filter := request.GET.get('format', ''):
        filter_items = filter_items.filter(format=format_filter)
        
    # Price filter
    if min_price := request.GET.get('min_price', ''):
        filter_items = filter_items.filter(price__gte=min_price)

    if max_price := request.GET.get('max_price', ''):
        filter_items = filter_items.filter(price__lte=max_price)

    # Genre filter
    if genre_filter := request.GET.get('genre', '').lower():
        filter_items = filter_items.filter(genre=genre_filter)

    # Carton filter
    if carton_filter := request.GET.get('carton', '').upper():
        filter_items = filter_items.filter(carton=carton_filter)

    filter_items = filter_items[::-1] # Reverse to the latest offer  
    images = [Image.objects.filter(item_id=item.pk).first() for item in filter_items]

    items = list(zip(filter_items, images))

    paginator = Paginator(items, 20)
    
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, "dashboard/user-items.html", {
        "page_obj": page_obj,
        "format_filter": format_filter,
        "min_price": min_price,  
        "max_price": max_price,
        "genres": GENRES,
        "genre_filter": genre_filter,
        "carton_filter": carton_filter
    })
    

application/dashboard/templates/dashboard/user-items.html
{% extends 'core/base.html' %}

{% block title %}Dashboard{% endblock %}

{% block content %}
<form method="get" action="{% url 'dashboard:user-items' %}" class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <p class="fs-3 mb-3">Filtry</p>
    <div class="row">
        <div class="col-xl-2">
            <select name="format" class="form-control mb-3">
                <option value="">Format płyty</option>
                <option value="3" {% if format_filter == '3' %}selected{% endif %}>LP</option>
                <option value="1" {% if format_filter == '1' %}selected{% endif %}>CD</option>
                <option value="2" {% if format_filter == '2' %}selected{% endif %}>DVD</option>
            </select>
        </div>
        <div class="col-xl-2">
            <select name="genre" class="form-control mb-3">
                <option value="">Gatunek</option>
                {% for genre in genres %}
                    <option value="{{ genre.0 }}" {% if genre_filter == genre.0 %}selected{% endif %}>{{ genre.1 }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="col-xl-2">
            <input name="carton" class="form-control mb-3" type="text" value="{{ carton }}" placeholder="Karton">
        </div>
        <div class="col-xl-2">
            <input name="min_price" class="form-control mb-3" type="number" value="{{ min_price }}" placeholder="Cena minimalna">
        </div>
        <div class="col-xl-2">
            <input name="max_price" class="form-control mb-3" type="number" value="{{ max_price }}" placeholder="Cena maksymalna">
        </div>
    </div>

    <input name="offername" class="form-control mb-3" type="text" value="{{ offername }}" placeholder="Znajdź ofertę">

    <button class="btn btn-success btn-lg">Szukaj</button>
    <button><a href="{% url 'dashboard:user-items' %}" class="btn btn-success btn-lg">Wyczyść</a></button>
</form>

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <div class="flex justify-content-between">
        <h2 class="mb-12 fs-3 text-center">Twoje oferty</h2><br>
        <nav aria-label="Pagination">
            <ul class="pagination justify-content-center mt-4">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Poprzednia</a>
                </li>
                {% endif %}
        
                {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                <li class="page-item active" aria-current="page">
                    <span class="page-link">{{ num }}</span>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                </li>
                {% endif %}
                {% endfor %}
        
                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">Następna</a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </div>

    <div class="table-responsive">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>
                        <p class="fs-4">Oferta</p>
                    </th>
                    <th>
                        <p class="fs-4">Zdjęcie</p>
                    </th>
                    <th>
                        <p class="fs-4">Tytuł</p>
                    </th>
                    <th>
                        <p class="fs-4">Cena</p>
                    </th>
                    <th>
                        <p class="fs-4">Karton</p>
                    </th>
                    <th>
                        <p class="fs-4">Edytuj</p>
                    </th>
                    <th>
                        <p class="fs-4">Usuń</p>
                    </th>
                </tr>
            </thead>
            <form method="POST" action="{% url 'item:edit-offers' %}">
                {% csrf_token %}
                <div id="edit-items" style="display: none;">
                    <input id="new-carton" name="new-carton" class="form-control mb-3" type="text" placeholder="Zmień karton">
                    <input id="new-price" name="new-price" class="form-control mb-3" type="text" placeholder="Zmień cenę">
                    <button type="submit" class="btn btn-success btn-lg mb-3" style="background-color: #157347">Edytuj wybrane</button>
                </div>
            <tbody>
                {% for item in page_obj  %}
                <tr>
                    <td>
                        <input class="form-check-input" type="checkbox" name="selected-id-items" value="{{ item.0.id }}" id="checkbox">
                    </td>
                    <td style="width: 10%">
                        <img src="/media/{{ item.1.url }}" class="img-fluid">
                    </td>
                    <td>
                        <a href="{% url 'item:detail' item.0.id %}">
                            <h2 class="text-xl">{{ item.0.name }}</h2>
                        </a>
                    </td>
                    <td>
                        <p class="text-xl">{{ item.0.price }} zł</p>
                    </td>
                    <td>
                        <p class="text-xl">{{ item.0.carton }}</p>
                    </td>
                    <td style="text-align: center">
                        <a href="{% url 'item:edit' item.0.id %}" class="btn btn-primary">Edytuj</a>
                    </td>
                    <td style="text-align: center">
                        <button type="button" class="btn delete" data-bs-toggle="modal" data-bs-target="#confirmModal{{ item.0.id }}">Usuń</button>
                    </td>
                </tr>

                <!-- Modal -->
                <div class="modal fade" id="confirmModal{{ item.0.id }}" tabindex="-1" aria-labelledby="confirmModalLabel{{ item.0.id }}" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="confirmModalLabel{{ item.0.id }}">Potwierdzenie usunięcia</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">Czy na pewno chcesz usunąć tę ofertę?</div>
                            <div class="modal-footer">
                                <a href="{% url 'item:delete' item.0.id %}" class="btn btn-danger">Usuń</a>
                                <button type="button" class="btn" data-bs-dismiss="modal">Anuluj</button>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </tbody>
        </table>
    </form>

    </div>
</div>

<script>
    const checkboxes = document.querySelectorAll('input[type="checkbox"]');
    const editItems = document.getElementById('edit-items');

    checkboxes.forEach(checkbox => {
        checkbox.addEventListener('change', () => {
            const checkedCheckboxes = document.querySelectorAll('input[type="checkbox"]:checked');
            if (checkedCheckboxes.length > 0) {
                editItems.style.display = 'block';
            } else {
                editItems.style.display = 'none';
            }
        });
    });

    function handleCheckboxClick(e) {
        let inBetween = false;
        if (e.shiftKey && this.checked) {
          checkboxes.forEach(checkbox => {
            if (checkbox === this || checkbox === lastChecked) {
              inBetween = !inBetween;
            }
      
            if (inBetween) {
              checkbox.checked = true;
            }
          });
        }
        
        lastChecked = this;
      }
      
    checkboxes.forEach(checkbox => checkbox.addEventListener('click', handleCheckboxClick));
</script>

<style>
    td, th{
        text-align: center;
    }

    .delete{
        background-color: #bb2d3b; 
        color: white;
    }
</style>
{% endblock %}