application/application/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user_payment.views import stripe_webhook

urlpatterns = [
    path("", include('core.urls')),
    path("oferty/", include('item.urls')),
    path("dashboard/", include('dashboard.urls')),
    path("payment/", include('user_payment.urls')),
    path("chat/", include('chat.urls')),
	path('stripe_webhook', stripe_webhook, name='stripe_webhook'),
    path("dostawa/", include('delivery.urls')),
    path("admin/", admin.site.urls),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

application/chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path("", views.index, name='chat'),
    path("create-room/<str:uuid>", views.create_room, name='create-room'),
    path("chat-admin/", views.chat_admin, name="chat-admin")
]

application/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path("", views.home, name='home'),
    path("koszyk/", views.cart, name='user-cart'),
    path('koszyk/remove/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path("ulubiony/", views.favorite, name='favorite'),
    path("kontakt/", views.contact, name='contact'),
    path("rejestracja/", views.signup, name='signup'),
    path("login/", auth_views.LoginView.as_view(template_name="core/login.html",authentication_form=LoginForm), name='login'),
    path("wyloguj/", auth_views.LogoutView.as_view(next_page='core:login'), name='logout'),
]

application/item/urls.py
from django.urls import path
from . import views

app_name = "item"

urlpatterns = [
    path("", views.items, name="items"),
    path("nowa-oferta/", views.new_item, name="new-item"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/edit/", views.edit_item, name="edit"),
    path("edit-offers/", views.edit_items, name="edit-offers"),
    path('favorite/<int:pk>/', views.toggle_favorite, name='favorite'),
]

application/item/models.py
from django.contrib.auth.models import User
from django.db import models

CONDITONS = (
    ("M", "Mint (M)"),
    ("M-", "Near Mint (NM or M-)"),
    ("EX", "Excellent (EX)"),
    ("VG+", "Very Good Plus (VG+)"),
    ("VG", "Very Good (VG)"),
    ("G", "Good (G)"),
    ("F", "Fair (F)"),
)

GENRES = (
    ('Ballada', 'Ballada'),
    ('Blues, Rhythm\'n\'Blues', 'Blues, Rhythm\'n\'Blues'),
    ('Country', 'Country'),
    ('Dance', 'Dance'),
    ('Disco polo, Party, Karaoke', 'Disco polo, Party, Karaoke'),
    ('Dla dzieci', 'Dla dzieci'),
    ('Ethno, Folk, World music', 'Ethno, Folk, World music'),
    ('Jazz, Swing', 'Jazz, Swing'),
    ('Kolędy', 'Kolędy'),
    ('Metal', 'Metal'),
    ('Muzyka alternatywna', 'Muzyka alternatywna'),
    ('Muzyka elektroniczna', 'Muzyka elektroniczna'),
    ('Muzyka filmowa', 'Muzyka filmowa'),
    ('Muzyka klasyczna', 'Muzyka klasyczna'),
    ('Muzyka religijna', 'Muzyka religijna'),
    ('Nowe brzmienia', 'Nowe brzmienia'),
    ('Opera, Operetka', 'Opera, Operetka'),
    ('Pop', 'Pop'),
    ('Rap, Hip-Hop', 'Rap, Hip-Hop'),
    ('Reggae, Ska', 'Reggae, Ska'),
    ('Rock', 'Rock'),
    ('Rock\'n\'roll', 'Rock\'n\'roll'),
    ('Single', 'Single'),
    ('Składanki', 'Składanki'),
    ('Soul, Funk', 'Soul, Funk'),
    ('Synth-pop', 'Synth-pop'),
    ('Pozostałe', 'Pozostałe'),
    ('Zestawy, pakiety', 'Zestawy, pakiety'),
    
)

class Format(models.Model):
    name = models.CharField(max_length=255)
    
    def __str__(self) -> str:
        return self.name

class Item(models.Model):
    name = models.CharField(max_length=255)
    format = models.ForeignKey(Format, related_name="items", on_delete=models.CASCADE, default=1)
    label = models.CharField(max_length=255, null=True, default="-")
    country = models.CharField(max_length=255, null=True, default="-")
    year = models.CharField(max_length=255, null=True, default="-")
    genre = models.CharField(choices=GENRES, default="ballad", max_length=50)
    condition = models.CharField(choices=CONDITONS, default="M-", max_length=50)
    price = models.FloatField()
    carton = models.CharField(max_length=5, default="-")
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name="items", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self) -> str:
        return self.name

    def save(self, *args, **kwargs):
        self.carton = self.carton.upper()
        super().save(*args, **kwargs)
    
class Image(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    url = models.ImageField(upload_to='item_images', null=False, blank=False)
    
class FavoriteItem(models.Model):
    item_id = models.ForeignKey(Item, null=False, blank=False, on_delete=models.CASCADE)

application/item/forms.py
from django import forms
from .models import Item

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'

class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True


class MultipleFileField(forms.FileField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput())
        super().__init__(*args, required=False, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            return [single_file_clean(d, initial) for d in data]
        else:
            return single_file_clean(data, initial)


class FileFieldForm(forms.Form):
    images = MultipleFileField()

class NewItemForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['label'].required = False
        self.fields['country'].required = False
        self.fields['year'].required = False
        
    class Meta:
        model = Item
        fields = ('name', 'format', 'label', 'country', 'year', 'genre', 'condition', 'price', 'carton')
        
        widgets = {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES,
            }),
            'format': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'label': forms.TextInput(attrs={
                'class': INPUT_CLASSES,
                "placeholder": "-"
            }),
            'country': forms.TextInput(attrs={
                'class': INPUT_CLASSES,
                "placeholder": "-",
            }),
            'year': forms.TextInput(attrs={
                'class': INPUT_CLASSES,
                "placeholder": "-"
            }),
            'genre': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'condition': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.ClearableFileInput(attrs={
                'class': INPUT_CLASSES,
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'carton': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
        }
        
class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'format', 'label', 'country', 'year', 'genre', 'condition', 'price', 'carton')
        
        widgets = {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'format': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'label': forms.TextInput(attrs={
                'class': INPUT_CLASSES,
                "required": False
            }),
            'country': forms.TextInput(attrs={
                'class': INPUT_CLASSES,
                "required": False
            }),
            'year': forms.TextInput(attrs={
                'class': INPUT_CLASSES,
                "required": False
            }),
            'genre': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'condition': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.ClearableFileInput(attrs={
                'class': INPUT_CLASSES,
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'carton': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
        }

class EditItemsForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['price'].required = False
        self.fields['carton'].required = False
        
    class Meta:
        model = Item
        fields = ('price', 'carton')
        
        widgets = {
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'carton': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
        }
  

application/item/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponse
from django.db.models import Q
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from random import randint
from .forms import NewItemForm, EditItemForm, FileFieldForm
from django.views.generic.edit import FormView
from .models import Item, Image, FavoriteItem, GENRES

MAX_IMAGES = 6

def sort_items(items, sort_by):
    if sort_by == 'latest_offer':
        return sorted(items, key=lambda x: x.created_at, reverse=True)
    elif sort_by == 'lowest_price':
        return sorted(items, key=lambda x: x.price)
    elif sort_by == 'highest_price':
        return sorted(items, key=lambda x: x.price, reverse=True)
    
    return items

def items(request):
    filter_items = Item.objects.all()

    # Name filter
    if name := request.GET.get('offername', ''):
        filter_items = filter_items.filter(Q(name__icontains=name))

    # Format filter
    if format_filter := request.GET.get('format', ''):
        filter_items = filter_items.filter(format=format_filter)
        
    # Price filter
    if min_price := request.GET.get('min_price', ''):
        filter_items = filter_items.filter(price__gte=min_price)

    if max_price := request.GET.get('max_price', ''):
        filter_items = filter_items.filter(price__lte=max_price)

    # Genre filter
    if genre_filter := request.GET.get('genre', ''):
        filter_items = filter_items.filter(genre=genre_filter)

    # Carton filter
    if carton_filter := request.GET.get('carton', '').upper():
        filter_items = filter_items.filter(carton=carton_filter)

    if sort_by := request.GET.get('sort-by', ''):
        filter_items = sort_items(filter_items, sort_by)
    
    images = [Image.objects.filter(item_id=item.pk).first() for item in filter_items]

    items = list(zip(filter_items, images))

    paginator = Paginator(items, 20)
    
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    return render(request, "item/items.html", {
        "page_obj": page_obj,
        "query": name,
        "format_filter": format_filter,
        "min_price": min_price,  
        "max_price": max_price,
        "genres": GENRES,
        "genre_filter": genre_filter,
        "sort_by": sort_by,
    })    

def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    images = Image.objects.filter(item_id=pk)
    
    random_offers = randint(0, len(Item.objects.filter(is_sold=False))-6) if len(Item.objects.filter(is_sold=False)) > 6 else 0
    filter_related_items = Item.objects.filter(format=item.format, is_sold=False).exclude(pk=pk)[random_offers:random_offers+6]
    related_images = [Image.objects.filter(item_id=item.pk).first() for item in filter_related_items]
    related_items = zip(filter_related_items, related_images)
    is_followed = FavoriteItem.objects.filter(item_id=item).exists()
    
    return render(request, "item/detail.html", {
        "item": item,
        "images": images,
        'related_items': related_items,
        "is_followed": is_followed
    })

class NewItemFormView(FormView):
    form_class = NewItemForm
    success_url = "/"

    def form_valid(self, form):
        item = form.save(commit=False)
        item.created_by = self.request.user
        item.save()

        images = self.request.FILES.getlist("images")
        for image in images:
            Image.objects.create(item=item, url=image)

        return super().form_valid(form)

@login_required
def new_item(request):
    if request.method == "POST":
        form = NewItemForm(request.POST, request.FILES)
        if len(request.FILES.getlist("images")) <= MAX_IMAGES and form.is_valid():
            return NewItemFormView.as_view()(request)
        
        image_form = FileFieldForm()
        
        if len(request.FILES.getlist("images")) > MAX_IMAGES:
            messages.warning(request, "Maksymalnie 6 zdjęć na ofertę")
    else:
        form = NewItemForm()
        image_form = FileFieldForm()

    return render(request, 'item/form.html', {
        "form": form,
        "imageForm": image_form,
        "max_images": MAX_IMAGES,
        "title": "Nowa oferta"
    })
    
@login_required
def edit_item(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    old_images = Image.objects.filter(item_id=item.pk).all()

    if request.method == "POST":
        form = EditItemForm(request.POST, request.FILES, instance=item)
        new_images = request.FILES.getlist("images")
        
        if form.is_valid() and len(request.FILES.getlist("images")) <= MAX_IMAGES:
            form.save()
            
            if new_images:
                for image in old_images:
                    image.delete()
                
                for image in new_images:
                    Image.objects.create(item=item, url=image)
            
            return redirect("item:detail", pk=item.id)
        else:
            image_form = FileFieldForm()
            messages.warning(request, "Maksymalnie 6 zdjęć na ofertę")
        
    else:
        form = EditItemForm(instance=item)
        image_form = FileFieldForm(initial={"images": old_images})
    
    return render(request, 'item/form.html', {
        "form": form,
        "imageForm": image_form,
        "max_images": MAX_IMAGES,
        "title": "Edytuj ofertę"
    })

@login_required
def edit_items(request):
    if request.method != 'POST':
        return
    
    selected_items = request.POST.getlist('selected-id-items')
    new_price = request.POST.get('new-price', '')
    new_carton = request.POST.get('new-carton', '')
    items = Item.objects.filter(id__in=selected_items)

    for item in items:
        if new_price:
            item.price = new_price
        if new_carton:
            item.carton =  new_carton
        item.save()

    return redirect('dashboard:user-items')  
  
@login_required
def delete(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    item.delete()
    
    return redirect("dashboard:user-items")

@login_required
def toggle_favorite(request, pk):
    item = Item.objects.get(pk=pk)  

    try:
        favorite_item = FavoriteItem.objects.get(item_id=item)
        # If it exists, delete it
        favorite_item.delete()
    except FavoriteItem.DoesNotExist:
        # If it doesn't exist, create a new instance
        new_instance = FavoriteItem(item_id=item)
        new_instance.save()

    return redirect('item:detail', pk=pk)

application/item/templates/item/detail.html
{% extends 'core/base.html' %}

{% block title%}{{ item.name }}{% endblock %}

{% block content %}

<div class="row">
    <div class="col-xl-6">
        <img id="main-image" src="/media/{{ images.0.url }}" data-original="/media/{{ images.0.url }}" class="rounded-xl img-fluid">
        <div class="row row-cols-6 gap-3 mt-4">
            {% for image in images %}
                <img src="/media/{{ image.url }}" class="subimage rounded-xl img-fluid" onclick="changeIndex('{{ image.url }}')">
            {% endfor %}
        </div>
    </div>

    <div class="col-xl-6 p-4 bg-light rounded-xl">
        <span class="d-flex justify-content-between">
            <h1 class="mb-4 text-3xl"><strong>{{ item.name }}</strong> </h1>
            {% comment %} Follow {% endcomment %}
            {% if user.is_authenticated %}
                <a href="{% url 'item:favorite' pk=item.pk %}" class="favorite-toggle">
                    {% if is_followed %}
                        <img id="fill-heart-icon" src="/media/assets/heart-fill28.svg"/>  
                    {% else %}
                        <img id="heart-icon" src="/media/assets/heart28.svg"/>  
                    {% endif %}
                </a>
            {% else %}
                <p>Please <a href="{% url 'login' %}">log in</a> to favorite this item.</p>
            {% endif %}
        </span>
        <p class="fs-5">Gatunek: {{ item.genre }}</p>
        <p class="fs-5">Wytwórnia: {{ item.label }}</p>
        <p class="fs-5">Kraj pochodzenia: {{ item.country }}</p>
        <p class="fs-5">Rok: {{ item.year }}</p>
        <p class="fs-5">Stan płyty: {{ item.condition }}</p>
        <p class="fs-5">Sprzedawca: {{ item.created_by.username }}</p>
        <p class="fs-2"><strong>{{ item.price }} zł</strong></p>

        {% if request.user == item.created_by %}
            <p class="fs-2"><strong>Karton: </strong>{{ item.carton }}</p>
        {% else %}  
            <a href="#" class="btn btn-success mt-6 w-50">Kup</a>
            <form method="post" action="{% url 'core:user-cart' %}">
                {% csrf_token %}
                <input type="hidden" name="item_id" value="{{ item.id }}">
                <button type="submit" class="btn btn-success mt-6 w-50" style="background-color: #198754">Dodaj do koszyka</button>
            </form>
        {% endif %}
    </div>
</div>

{% if item.tracklist %}
    <div class="mt-6 p-4 bg-light rounded-xl">
        <h2 class="mb-4 text-2xl">Lista utworów</h2>
        {{ item.tracklist }}
    </div>
{% endif %}


<div class="mt-6 p-4 bg-light rounded-xl">
    <h2 class="mb-4 text-2xl">Jak oceniamy płyty</h2>
    <ul>
        <li><b>IDEALNY (M)</b> -&nbsp;płyta nowa lub nie odtwarzana, bez najmniejszych śladów użycia.</li>
        <li><b>NIEMALŻE IDEALNY (M-)</b> - praktycznie idealna, jednak odtwarzana raz lub kilka razy.</li>
        <li><b>DOSKONAŁY (EX)</b> - odtwarzana, z widoczną niewielką ilością delikatnych rysek lub inną bardzo drobną wadą nie wpływającą na jakość dźwięku.</li>
        <li><b>BARDZO DOBRY Z PLUSEM (VG+)</b> - bardzo dobry stan, może mieć drobne ryski. Odtwarzana wiele razy, jednak z dużą dbałością.</li>
        <li><b>BARDZO DOBRY (VG) </b> - nadal całkiem dobry stan, może mieć więcej drobnych rysek, lub może posiadać głębszą rysę. Odtwarzana wiele razy.</li>
        <li><b>DOBRY</b> <b>(G)</b> - grana bardzo często, może posiadać widoczne głębsze rysy.</li>
        <li><b>ZŁY</b> <b>(F)</b> - poważniejsze rysy.</li>
    </ul>
</div>

<div class="mt-6 px-6 py-12 bg-light rounded-xl">
    <h2 class="mb-4 text-2xl text-center">Oferty, które mogą ci się podobać</h2>

    <div class="row cols-xl-2">
        {% for item in related_items %}
            <div class="col">
                <a href="{% url 'item:detail' item.0.id %}">
                    <div>
                        <img src="/media/{{ item.1.url }}" class="rounded-xl img-fluid">
                    </div>

                    <div class="p-4 bg-white rounded-xl">
                        <h2 class="text-2xl">{{ item.0.name }}</h2>
                        <p class="text-gray-500">{{ item.0.price }} zł</p>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/viewerjs/1.11.1/viewer.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/viewerjs/1.11.1/viewer.min.js"></script>

<script>
    // Images preview
    let viewer = new Viewer(document.getElementById('main-image'), {
        inline: false,
        viewed: function() {        },
        toolbar: {
            zoomIn: true,
            zoomOut: true,
            oneToOne: false,
            rotateLeft: true,
            rotateRight: true,
            reset: true,
        },
    });
 
    function changeIndex(url) {
        let mainImage = document.getElementById('main-image');
        mainImage.src = "/media/" + url;
    }

    // Change color of heart
    const heartIcon = document.getElementById('heart-icon');
    const fillHeartIcon = document.getElementById('fill-heart-icon');

    heartIcon.addEventListener('click', function() {
        heartIcon.style.display = heartIcon.style.display === 'none' ? '' : 'none';
    });
</script>
<style>

    #main-image{
        cursor: pointer;
    }

    .subimage {
        opacity: 0.95;
        transition: transform 0.3s;
    }

    .subimage:hover {
        opacity: 1;
        cursor: pointer;
    }
</style>
{% endblock %}

application/item/templates/item/form.html
{% extends 'core/base.html' %}

{% block title%}{{ title }}{% endblock %}

{% block content %}

<h1 class="mb-6 display-4">{{ title }}</h1>

<form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-4">
        {{ form.as_p }}
        {{ imageForm.as_p }}
        <div id="image-preview" class="row row-cols-4 gap-3 mt-4">
            {% for image in imageForm.images.value %}
                <div class="col">
                    <img src="/media/{{ image.url }}" alt="Image Preview" class="img-fluid">
                </div>
            {% endfor %}
        </div>
    </div>

    {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>
    {% endif %}
    
    <button class="mt-6 btn btn-success btn-lg">Wystaw</button>
</form>

<script>
    function previewImages() {
        let previewContainer = document.getElementById('image-preview')
        let files = [...document.getElementById('id_images').files]
        previewContainer.innerHTML = ''
    
        for (let i = 0; i < {{ max_images }}; i++) {
            let file = files[i]
            let reader = new FileReader()
    
            reader.onload = function (event) {
                let img = document.createElement('img')
                img.className = 'preview-image'
                img.src = event.target.result
                previewContainer.appendChild(img)
            }
    
            reader.readAsDataURL(file)
        }
    }
    
    let id_images = document.getElementById('id_images')
    if (id_images)
    {
        id_images.addEventListener('change', previewImages)
    } 
    
</script>

{% endblock %}

application/item/templates/item/items.html
{% extends 'core/base.html' %}

{% block title%}Oferty{% endblock %}

{% block content %}
<div class="pb-6 row row-cols-4 g-4 bg-gray-100">
    <div class="col-12 col-md-3">
        <h1 class="fs-2 mb-3">Filtry</h1>
        <form id="filter-form" method="get" action="{% url 'item:items' %}">
            <p class="font-weight-bold">Znajdź ofertę</p>

            <input name="offername" class="form-control mb-3" type="text" value="{{ query }}" placeholder="Tytuł oferty">

            <hr class="my-3">

            <p class="font-weight-bold">Formaty</p>

            <select name="format" class="form-control mb-3">
                <option value="">Format płyty</option>
                <option value="3" {% if format_filter == '3' %}selected{% endif %}>LP</option>
                <option value="1" {% if format_filter == '1' %}selected{% endif %}>CD</option>
                <option value="2" {% if format_filter == '2' %}selected{% endif %}>DVD</option>
            </select>

            <hr class="my-3">
            
            <p class="font-weight-bold">Gatunki</p>

            <select name="genre" class="form-control mb-3">
                <option value="">Gatunek</option>
                {% for genre in genres %}
                    <option value="{{ genre.1 }}" {% if genre_filter == genre.1 %}selected{% endif %}>{{ genre.1 }}</option>
                {% endfor %}
            </select>

            <hr class="my-3">

            <p class="font-weight-bold">Cena</p>

            <div class="col-xl-6">
                <input name="min_price" class="form-control mb-3" type="number" value="{{ min_price }}" placeholder="Cena minimalna">
                <input name="max_price" class="form-control mb-3" type="number" value="{{ max_price }}" placeholder="Cena maksymalna">
            </div>

            <hr class="my-3">

            <div class="row">
                <div class="col-1">
                    <button class="btn btn-success btn-lg mb-3">Szukaj</button>
                    <button><a href="{% url 'item:items' %}" class="btn btn-success btn-lg">Wyczyść</a></button>
                </div>
            </div>

    </div>

    <div class="col-12 col-md-9">
        <nav aria-label="Pagination">
            <ul class="pagination mb-4">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Poprzednia</a>
                </li>
                {% endif %}
        
                {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                <li class="page-item active" aria-current="page">
                    <span class="page-link">{{ num }}</span>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                </li>
                {% endif %}
                {% endfor %}
        
                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">Następna</a>
                </li>
                {% endif %}

            </ul>
                <select name="sort-by" class="form-control mb-3 w-25" onchange="document.getElementById('filter-form').submit()">
                    <option value="">Sortuj</option>
                    <option value="latest_offer" {% if sort_by == 'latest_offer' %}selected{% endif %}>Od najnowszej</option>
                    <option value="lowest_price" {% if sort_by == 'lowest_price' %}selected{% endif %}>Od najtańszej</option>
                    <option value="highest_price" {% if sort_by == 'highest_price' %}selected{% endif %}>Od najdroższej</option>
                </select>
            </form>
        </nav>

        <div class="row row-cols-3 g-3">
            {% for item in page_obj %}
                <div class="col-xl-4">
                    <a href="{% url 'item:detail' item.0.id %}">
                        <div>
                            <img src="/media/{{ item.1.url }}" class="rounded-t-xl">
                        </div>

                        <div class="p-3 bg-white rounded-b-xl flex-wrap">
                            <p>{{ item.0.name }}</p>
                            <p class="fs-5">{{ item.0.price }} zł</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}