application/application/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user_payment.views import stripe_webhook

urlpatterns = [
    path("", include('core.urls')),
    path("oferty/", include('item.urls')),
    path("dashboard/", include('dashboard.urls')),
    path("payment/", include('user_payment.urls')),
    path("chat/", include('chat.urls')),
	path('stripe_webhook', stripe_webhook, name='stripe_webhook'),
    path("dostawa/", include('delivery.urls')),
    path("admin/", admin.site.urls),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

application/chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path("", views.index, name='chat'),
    path("create-room/<str:uuid>", views.create_room, name='create-room'),
    path("chat-admin/", views.chat_admin, name="chat-admin")
]

application/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path("", views.home, name='home'),
    path("koszyk/", views.cart, name='user-cart'),
    path('koszyk/remove/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path("ulubiony/", views.favorite, name='favorite'),
    path("kontakt/", views.contact, name='contact'),
    path("rejestracja/", views.signup, name='signup'),
    path("login/", auth_views.LoginView.as_view(template_name="core/login.html",authentication_form=LoginForm), name='login'),
    path("wyloguj/", auth_views.LogoutView.as_view(next_page='core:login'), name='logout'),
]

application/dashboard/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views
from item import views as item_views

app_name = 'dashboard'

urlpatterns = [
    path("", views.user_items, name='user-items'),
    path("<int:pk>/delete/", item_views.delete, name="delete"),
    path("<int:pk>/edit/", item_views.edit_item, name="edit"),
]

application/delivery/urls.py
from django.urls import path
from . import views

app_name = "dostawa"

urlpatterns = [
    path('zamówienia/', views.parcels, name='parcels'),
    path('utworz-zamowienie/', views.create_parcel, name='create_parcel'),
    path('status-zamowienia/<str:parcel_number>/', views.parcel_status, name='parcel_status'),
]

application/item/urls.py
from django.urls import path
from . import views

app_name = "item"

urlpatterns = [
    path("", views.items, name="items"),
    path("nowa-oferta/", views.new_item, name="new-item"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/edit/", views.edit_item, name="edit"),
    path("edit-offers/", views.edit_items, name="edit-offers"),
    path('favorite/<int:pk>/', views.toggle_favorite, name='favorite'),
]

application/user_payment/urls.py
from django.urls import path
from . import views

app_name = 'payment'

urlpatterns = [
	path('product_page', views.product_page, name='product_page'),
	path('payment_successful', views.payment_successful, name='payment_successful'),
	path('payment_cancelled', views.payment_cancelled, name='payment_cancelled'),
]

application/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class SingupFrom(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")
        
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': "Your username",
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': "Your email address",
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': "Your password",
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': "Repeat password",
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    
class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")
        
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': "Your username",
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': "Your password",
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

application/core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from item.models import Format, Item, Image, FavoriteItem
from .forms import SingupFrom

def home(request):
    items = Item.objects.filter(is_sold=False)[::-1][:6]
    images = [Image.objects.filter(item_id=item.pk).first() for item in items]
    newest_items = zip(items, images)
    formats = Format.objects.all()

    return render(request, 'core/home.html', {
        'formats': formats,
        'newest_items': newest_items,
    })

def contact(request):
    return render(request, 'core/contact.html')

def signup(request):
    if request.method == "POST":
        form = SingupFrom(request.POST)
        
        if form.is_valid():
            form.save()

            return redirect("/login/")
    else:
        form = SingupFrom()
    
    return render(request, 'core/signup.html', {
        "form": form
    })

def cart(request):
    if 'cart' not in request.session:
        request.session['cart'] = []  

    if request.method == 'POST' and 'item_id' in request.POST:
        add_to_cart(request)
        
    return render(request, 'core/cart.html', {
        'cart': request.session['cart'],
    })


def add_to_cart(request):
    item_id = request.POST['item_id']
    item = get_object_or_404(Item, id=item_id)
    image = Image.objects.filter(item_id=item.pk).first()

    item_data = {
        'id': item.id,
        "image": str(image.url),
        'name': item.name,
        'price': item.price,
    }

    cart = request.session['cart']
    if item_data not in cart:
        cart.append(item_data)
        request.session.modified = True

def remove_from_cart(request, item_id):
    if 'cart' in request.session:
        cart = request.session['cart']
        cart = [item for item in cart if item['id'] != item_id]
        request.session['cart'] = cart
        request.session.modified = True
    return redirect('core:user-cart')

def favorite(request):
    favorite_ids = FavoriteItem.objects.all()
    favorite = [item.item_id for item in favorite_ids]
    images = [Image.objects.filter(item_id=item.item_id).first() for item in favorite_ids]

    favorite_items = zip(favorite, images)
    
    return render(request, 'core/favorite.html', {
        'favorite_items': favorite_items,
    })

application/core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>{% block title %} {% endblock %} | Records Shop</title>
    <style>
        .icon:hover{
            filter: invert(50%) sepia(100%) saturate(1000%) hue-rotate(200deg) brightness(80%) contrast(120%);
        }
        @media (max-width: 600px) {
            .title {
                flex-direction: column;
            }

            .search{
                width: 50%;
            }
          }
    </style>
</head>
<body class="d-flex flex-column min-vh-100">
    <nav class="py-6 px-6 navbar navbar-expand-lg navbar-light bg-light border-bottom rounded-xl">
        <div class="container-fluid d-flex justify-content-between align-items-center">
            <form action="{% url 'item:items' %}" method="GET" class="title flex mb-3">
                <a href="/" class="navbar-brand text-xl font-semibold">Records shop</a>
                <span class='flex'>
                    <input type="text" name="offername" placeholder="Szukaj płyt" class="search text-lg px-4 rounded-l-lg focus:outline-none focus:ring-2 focus:ring-blue-400 border">
                    <button type="submit" class="bg-blue-500 hover:bg-blue-600 text-white text-lg font-semibold px-4 rounded-r-lg">Szukaj</button>
                </span>
            </form>

            <div class="flex gap-4">
                {% if request.user.is_authenticated %}

                    {% if request.user.is_staff %}
                        <a href="{% url 'chat:chat-admin' %}" class="text-lg font-semibold">                            
                            <span class="relative">
                                <img src="/media/assets/chat.svg" class="icon w-100" alt="Chat">
                            </span>
                        </a>
                        <a href="{% url 'dostawa:parcels' %}" class="text-lg font-semibold">Zamówienia</a>
                        <a href="{% url 'item:new-item' %}" class="text-lg font-semibold">Wystaw ofertę</a>
                        <a href="{% url 'dashboard:user-items' %}" class="text-lg font-semibold">Twoje oferty</a>
                    {% else %}
                        <a href="{% url 'dostawa:parcels' %}" class="text-lg font-semibold">
                            <span class="relative">
                                <img src="/media/assets/box.svg" class="icon w-100"  alt="Delivery">
                            </span>
                        </a>

                        <a href="{% url 'core:favorite' %}" class="text-lg font-semibold">
                            <span class="relative">
                                <img src="/media/assets/heart.svg" class="icon w-100" alt="Heart">
                                {% if follow_count > 0 %}
                                    <span class="absolute -bottom-2 -right-1 text-xs bg-red-500 text-white px-1 rounded-full">{{ follow_count }}</span>
                                {% endif %}
                            </span>
                        </a>

                        <a href="{% url 'chat:chat' %}" class="text-lg font-semibold">
                            <span class="relative">
                                <img src="/media/assets/chat.svg" class="icon w-100" alt="Chat">
                            </span>
                        </a>

                        <a href="{% url 'core:user-cart' %}" class="text-lg font-semibold">
                            <span class="relative">
                                <img src="/media/assets/cart.svg" class="icon w-100" alt="Cart">
                                {% if cart_count > 0 %}
                                    <span class="absolute -bottom-2 -right-2 text-xs bg-red-500 text-white px-1 rounded-full">{{ cart_count }}</span>
                                {% endif %}
                            </span>
                        </a>
                    {% endif %}
                    <a href="{% url 'core:logout' %}" class="text-lg font-semibold">Wyloguj się</a>
                {% else %}
                    <a href="{% url 'core:signup' %}" class="text-lg font-semibold">Rejestracja</a>
                    <a href="{% url 'core:login' %}" class="text-lg font-semibold">Logowanie</a>
                {% endif %}
            </div>
            
        </div>
    </nav>
    
    {% if messages %}
        <div class="alert alert-primary" role="alert">
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        </div>
    {% endif %}
    
    <div class="px-6 py-6">
        {% block content %}
        {% endblock %}
    </div>
    
    <footer class="py-6 px-6 bg-dark mt-auto">
        <div class="row">
            <div class="col-8 pr-10">
                <h3 class="mb-5 font-semibold text-light">O nas</h3>
                <p class="text-lg text-light">Lorem ipsum.</p>
            </div>
            <div class="col-4">
                <h3 class="mb-5 font-semibold text-light">Menu</h3>
                <ul class="list-unstyled">
                    <li><a href="#" class="text-lg text-teal-500">O nas</a></li>
                    <li><a href="{% url 'core:contact' %}" class="text-lg text-teal-500">Kontakt</a></li>
                    <li><a href="#" class="text-lg text-teal-500">Polityka prywatności</a></li>
                    <li><a href="#" class="text-lg text-teal-500">Regulamin</a></li>
                </ul>
            </div>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

application/core/templates/core/cart.html
{% extends 'core/base.html' %}

{% block title %}Koszyk{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            {% if cart %}
                <h1 class="mb-12 text-2xl text-center">Koszyk</h1>
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">Zdjęcie</th>
                                <th scope="col">Produkt</th>
                                <th scope="col">Cena</th>
                                <th scope="col">Usuń</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in cart %}
                            <tr>
                                <td style="width: 10%">
                                    <img src="/media/{{ item.image }}" class="img-fluid">
                                </td>
                                <td><a href="{% url 'item:detail' item.id %}">{{ item.name }}</a></td>
                                <td class="price">{{ item.price }}</td>
                                <td>
                                    <a href="{% url 'core:remove_from_cart' item.id %}">
                                        <div style="width: 30px;">
                                            <svg fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
                                                <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12"></path>
                                            </svg>
                                        </div>
                                    </a>
                                </td>
                            </tr>
                            
                            {% endfor %} 
                        </tbody>
                    </table>
                    <div class="text-left">
                        <h4 id="total">Suma: </h4>
                    </div>
                    <a href="{% url 'payment:product_page' %}" class="btn btn-primary btn-lg mt-4">Płatność</a>
            
            {% else %}
                <h1 class="mb-12 text-2xl text-center">Twój koszyk jest pusty</h1>
            {% endif %}
        </div>
    </div>
</div>

<script>
    const items = document.querySelectorAll('.price')
    let total = 0

    items.forEach(item => {
        const price = parseFloat(item.innerHTML)
        total += price
    });

    const totalElement = document.getElementById('total');
    if (totalElement){
        totalElement.textContent += total.toFixed(2)
    }
</script>
{% endblock %}

application/core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %}Contact{% endblock %}

{% block content %}
    The contact page
{% endblock %}

application/core/templates/core/favorite.html
{% extends 'core/base.html' %}

{% block title %}Ulubione{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            {% if follow_count %}
                <h1 class="mb-12 text-2xl text-center">Ulubione</h1>
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">Zdjęcie</th>
                                <th scope="col">Produkt</th>
                                <th scope="col">Cena</th>
                                <th scope="col">Usuń</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in favorite_items %}
                            <tr>
                                <td style="width: 10%">
                                    <img src="/media/{{ item.1.url }}" class="img-fluid">
                                </td>
                                <td><a href="{% url 'item:detail' item.0.id %}">{{ item.0.name }}</a></td>
                                <td class="price">{{ item.0.price }}</td>
                                <td>
                                    <a href="{% url 'item:favorite' item.0.id %}">
                                        <div style="width: 30px;">
                                            <svg fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
                                                <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12"></path>
                                            </svg>
                                        </div>
                                    </a>
                                </td>
                            </tr>
                            
                            {% endfor %} 
                        </tbody>
                    </table>
            
            {% else %}
                <h1 class="mb-12 text-2xl text-center">Nie masz ulubionych produktów</h1>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

application/core/templates/core/home.html
{% extends 'core/base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}
<div id="carouselExample" class="carousel slide" data-bs-ride="carousel">
    <ol class="carousel-indicators">
      <li data-bs-target="#carouselExample" data-bs-slide-to="0" class="active"></li>
      <li data-bs-target="#carouselExample" data-bs-slide-to="1"></li>
      <li data-bs-target="#carouselExample" data-bs-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <a href="#">
            <img src="/media/assets/baner.png" class="d-block w-100" alt="Image 1">
        </a>
      </div>
      <div class="carousel-item">
        <a href="#">
            <img src="/media/assets/baner2.png" class="d-block w-100" alt="Image 2">
        </a>
      </div>
      <div class="carousel-item">
        <a href="#">
            <img src="/media/assets/baner3.png" class="d-block w-100" alt="Image 3">
        </a>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExample" role="button" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExample" role="button" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </a>
  </div>

<div class="mt-6 px-6 py-12 bg-light rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Najnowsze oferty</h2>
    <div class="d-flex justify-content-center">
        <div class="w-70 row g-3">
            {% for item in newest_items %}
                <a href="{% url 'item:detail' item.0.id %}" class="col-lg-4 col-md-6">
                    <div>
                        <img src="/media/{{ item.1.url }}" class="rounded-top border border-gray">
                    </div>

                    <div class="p-6 bg-white rounded-bottom">
                        <h2 class="text-2xl">{{ item.0.name }}</h2>
                        <p class="text-gray-500">Price: {{ item.0.price }}</p>
                    </div>
                </a>
            {% endfor %}
        </div>
    </div>
</div>

<div class="mt-6 px-6 py-12 bg-light rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Formaty</h2>

    <div class="row g-3">
        {% for format in formats %}
            <div class="col">
                <a href="{% url 'item:items' %}?format={{ format.id }}">
                    <div class="p-6 bg-white rounded-bottom-xl">
                        <h2 class="text-2xl">{{ format.name }}</h2>
                        <p class="text-gray-500">{{ format.items.count }} ofert</p>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

application/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}
<div class="w-50 my-6 mx-auto p-6 bg-light rounded-xl">
    <h1 class="mb-6 text-3xl">Zaloguj</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="form-label mb-2">Nazwa użytkownika</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="form-label mb-2">Hasło</label><br>
            {{ form.password }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-danger rounded-xl text-white">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="btn btn-success btn-lg">Zaloguj</button>
    </form>
</div>

{% endblock %}

application/core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="w-50 my-6 mx-auto p-6 bg-light rounded-xl">
    <h1 class="mb-6 text-3xl">Sign up</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="form-label mb-2">Nazwa użytkownika</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="form-label mb-2">Email</label><br>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="form-label mb-2">Hasło</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="form-label mb-2">Powtórz hasło</label><br>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-danger rounded-xl text-white">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="btn btn-success btn-lg">Zarejestruj</button>
    </form>
</div>

{% endblock %}